### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by annmedvid** [darde/github-graphql-pagination#1]
Hi Pablo :wave:
We appreciate your performed technical task and time you spent on it!
May I ask you to extend it by adding search functionality as well?
Please do it by opening PR to this repo.

BR, Anna

**Comment by darde** [comment]
Hi, Anna, thanks for asking this feature. I opened a PR, and I would appreciate your review.
https://github.com/darde/github-graphql-pagination/pull/3

**Comment by darde** [comment]
Issue closed because the required feature was already merged.
